apiVersion: v1
kind: Namespace
metadata:
  name: stack01
  labels:
    env: dev
    loc: us-east

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: fontend
#  namespace: kube-learn
#  labels:
#    env: dev
#    type: web
#spec:
#  containers:
   - init
      code
#  - image: httpd:latest
#    name: webcon
#    imagePullPolicy: Always
#    ports:
#    - name: apache
#      containerPort: 80
#      protocol: TCP
#    resources:
#      requests:
#        memory: 100Mi
#        cpu: 200m
#      limits:
#        memory: 200Mi
#        cpu: 300m
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: websvc
#  namespace: kube-learn
#  labels:
#    env: dev
#    type: web
#spec:
#  type: LoadBalancer
#  ports:
#  - name: apache
#    port: 80
#    protocol: TCP
#    targetPort: 80
#  selector:
#    env: dev
#    type: web
