apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: stack01
  labels:
    env: dev
    type: web
spec:
  containers:
  - image: httpd:latest
    imagePullPolicy: Always
    name: webapp
    ports:
    - containerPort: 80
      protocol: TCP
      name: apache
    resources:
      limits:
         cpu: 200m
         memory: 200Mi
      requests:
        cpu: 150m
        memory: 150Mi
